name: tp13
description: "A Flutter project with Google Maps and Place Picker integration."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.5
  place_picker: ^0.10.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
